#!/usr/bin/awk -f

function CmusInfo() {
    while("cmus-remote -Q"|getline) {
        if(/tag artist/) {
            for(i=3; i<=NF; i++) {
                artist=artist $i" "
            }
        }
        if(/tag title/) {
            t = NF;
            for(i=3; i<=NF; i++) {
                title=title $i" "
            }
        }
    }
    printf artist "- " title
}

BEGIN {
    CmusInfo()
}
